### PR TITLE
Limits

### PR DESCRIPTION
**Pull request by paladinlogic**
Port of the Limits submodule from the Ruby api library.

### CODE REVIEW

**Comment by jamiemtdwyer** [comment]
you'll need to remove the copyright statement

**Comment by paladinlogic** [comment]
Hah, sorry, that's in our code template. Forgot to remove it. 👍

**Comment by paladinlogic** [comment]
No activity on this? We find it's rather useful.

**Comment by flux627** [comment]
All pull requests require tests.

How does one use this?

**Comment by jamiemtdwyer** [comment]
Can you write tests for this using the tests in the Ruby gem as a template? https://github.com/Shopify/shopify_api/blob/master/test/limits_test.rb

**Comment by paladinlogic** [comment]
I have a pretty heavy load this week, but I'll get to it as soon as I can. Thank you for linking me to the ruby tests, it should be helpful.

**Comment by wowkin2** [comment]
Any progress on this?

**Comment by jamiemtdwyer** [comment]
I'll go ahead and fork this so I can release it in 4.0.0

**Comment by jamiemtdwyer** [comment]
Closed in favour of #266.

**Pull request closed without merging**
