### PR TITLE
[Feature] Add Dynamic api versioning

### LINKED ISSUE #339: Dynamic API Version support
Similar to https://github.com/Shopify/shopify_api/pull/600, so we don't have to manually update the gem on every API Version release.

Worth noting that the description of that PR is somewhat different from the final approach chosen.

### PR DESCRIPTION
**Pull request by smubbs**
This PR will automatically populate with the current API versions supported for the Shopify Admin API.

Hopefully, this should remove the requirement to manually update the list of current API versions.

### WHY are these changes introduced?

Fixes #339 

Versioning has been here a while and it's probably time we fix this manual update requirement. A manual system is fine, but it still causes issues with development and to not be able to select the currently available APIs, that is to say, to have to wait for this package to be updated every quarter is unreasonable. It is now 25 November, Release Candidate 2021-01 has been available for also 2 months now and it is still not supported here.

### WHAT is this pull request doing?

`ApiVersion.define_known_versions()` has been changed to make a request to https://app.shopify.com/services/apis.json and automatically populate the versions list.

Updated `TestCase.fake()` default to using an `url` when provided or constructing one when `endpoint` is provided.

Added payload `api_version.json` for call in `fake('apis'...)`
### Checklist

- [x] I have updated the CHANGELOG (if applicable)
- [x] I have followed the [Shopify Python](https://github.com/Shopify/shopify_python) guide

### CODE REVIEW

**Review by mllemango — APPROVED** [review]
Thank you for working on this! I've tested locally and this looks good!

**Comment by smubbs** [comment]
Thanks! Happy to help.

**Review by tanema — APPROVED** [review]

**Comment by andyw8** [comment]
(note that we're missing a change entry for this, even though the checkbox was checked).

**Comment by mllemango** [comment]
Good catch, I'll add an entry with the new release PR if thats fine.

**Pull request merged**
