### PR TITLE
Statsd support

### PR DESCRIPTION
**Pull request by orenmazor**
valuable for us. not sure if anybody else cares.

@kevinhughes27 @richardblair @perobertson

### CODE REVIEW

**Comment by kevinhughes27** [comment]
Code looks good to me and is a good example of how to add telemetry to this package. I'm not sure how I feel about merging as is though because it adds an extra dependency that not everyone will use. Any ideas on how to make this more optional?

**Comment by perobertson** [comment]
around the statsd code you can do something like this:
```python
try:
  from datadog import statsd
  tags = []
  statsd.increment('thing', tags=tags)
except ImportError:
  # datadog is optional
  pass
```

**Comment by jamiemtdwyer** [comment]
If you write a short guide on how to do this, I'd be happy to add it to the README but I'll echo Kevin's statement on not adding dependencies that not every consumer will need.

**Comment by wowkin2** [comment]
I don't think that this code should go to this repository, you can always patch library with anything you need, but not all developers use datadog.

**Pull request closed without merging**
