### PR TITLE
[Bug fix] - Return None when sanitizing shop domain if None passed in

### PR DESCRIPTION
**Pull request by NabeelAhsen**
### WHY are these changes introduced?

> **Bug:** `shop_url.sanitize_shop_domain(None)` returns `"none.myshopify.com"`
> * I just found out that `str(None) == "none"` in Python 😬 

~~This PR is intended to be a patch for shopify_python_api `v8.3`~~. It introduces a check to see if `shop_domain` is `None`.

### Releasing

~~I noticed that we've released `v8.4` already. Ideally, I'd like to release this as a patch for both `v8.4` and `v8.3.2`. Do we have a guide on how to do this?~~

This is intended to be a patch release.

### Checklist

- [x] I have updated the CHANGELOG (if applicable)
- [x] I have followed the [Shopify Python](https://github.com/Shopify/shopify_python) guide

### CODE REVIEW

**Review by mllemango — APPROVED** [review]
Hahaha TIL
Neat use of `or`

**Comment by NabeelAhsen** [comment]
@mllemango  Do we have a release strategy to patch this for release `v8.3`?

**Comment by andyw8** [comment]
We generally don't patch older release, what would prevent those on v8.3 from updating?

**Comment by NabeelAhsen** [comment]
> We generally don't patch older releases, what would prevent those on v8.3 from updating?

Oh good point, nothing's breaking I suppose

:shipit:

**Comment by NabeelAhsen** [comment]
I'm updating this PR to include a Changelog update + patch version bump as well

**Comment by mllemango** [comment]
Should we update the title of the PR to be Release v8.4.1 in this case?

**Comment by andyw8** [comment]
We should be using separate PRs for the changes and the releases.

**Comment by NabeelAhsen** [comment]
I've updated this PR to only include the bug fix, I'll draft a follow-up patch release in a separate PR

**Review by rezaansyed — APPROVED** [review]
LGTM!

**Pull request merged**
