### PR TITLE
Corrected use of renamed function `build_collection` that was `build_…

### PR DESCRIPTION
**Pull request by ChaseGuru**
Addresses https://github.com/Shopify/shopify_python_api/issues/411

### CODE REVIEW

**Comment by ChaseGuru** [comment]
I just signed the CLA.

**Comment by andyw8** [comment]
Looks good, can we add a test to `test/gift_card_test.py` to verify it?

**Review by mkevinosullivan — APPROVED** [review]

**Comment by mkevinosullivan** [comment]
I hit approve a little too soon!  As per @andyw8 comment, please add a test.

**Comment by ChaseGuru** [comment]
@mkevinosullivan I created a test.

**Comment by ChaseGuru** [comment]
I'm going to clean up a couple things I guess.

**Review by andyw8 — APPROVED** [review]

**Comment by ChaseGuru** [comment]
@andyw8 Thanks for the approval.  The code I pushed 6 minutes ago includes my cleanup.  I think it should be ready to merge whenever you guys feel good about it.

**Pull request merged**
