### PR TITLE
Some Improvements, fixed API Call Limits

### PR DESCRIPTION
**Pull request by antwal**
I have fixed some things, the important parts that you have to check are good for you are:

The version change with release, to support in the release name the levels "ALPHA, BETA, RELEASE_CANDIDATE, FINAL" as specified:

```
# version_info format: (MAJOR, MINOR, MICRO, RELEASE_LEVEL, SERIAL)
# inspired by Python's own sys.version_info, in order to be
# properly comparable using normal operarors, for example:
#  (6,1,0,'beta',0) < (6,1,0,'candidate',1) < (6,1,0,'candidate',2)
#  (6,1,0,'candidate',2) < (6,1,0,'final',0) < (6,1,2,'final',0)
```

I moved api call limits within the resource directory, but it has to be fixed
I changed the travis settings for the build

For the rest I have updated the changelog in the case check everything before accepting the PR.

### CODE REVIEW

**Comment by antwal** [comment]
I converted API Limits code from lib/shopify_api/limits.rb and test/limits_test.rb, now it works perfectly

**Comment by coler-j** [comment]
What was broken about the current `limits`?

**Comment by antwal** [comment]
@coler-j not working and tests failed

**Comment by antwal** [comment]
Can close this PR

**Pull request closed without merging**
