### PR TITLE
Allow new api version - 2023-07

### PR DESCRIPTION
**Pull request by PeterBalsdon**
### WHY are these changes introduced?

Allows access to the latest API version.

### WHAT is this pull request doing?

Added api version

### Checklist

- [x] I have updated the CHANGELOG (if applicable)
- [x] I have followed the [Shopify Python](https://github.com/Shopify/shopify_python) guide

### CODE REVIEW

**Review by kevinmora94 — APPROVED** [review]

**Comment by AndrewChau** [comment]
Hi team, any idea when this will be merged? Thanks

**Comment by TysonRV** [comment]
@hriks really looking forward to see this in

**Review by ilankessler — APPROVED** [review]

**Comment by kevinbroomepetlab** [comment]
+1 for this PR asap as old APIs deprecated

**Review by kevinbroomepetlab — APPROVED** [review]

**Comment by nbenouss** [comment]
Try to contact engineering@shopify.engineering , I have just sent an email, waiting now :) If you're about to +1 my message please send an email instead.

**Pull request closed without merging**
