### PR TITLE
Support for independently creating/modifying product images (closes #88)

### LINKED ISSUE #88: Support for independently creating/modifying product images.
Please correct me if I'm wrong, but at the moment the only way to create/update product images through the Python API is directly through a POST/PUT call to the product endpoint.

As per the [Shopify API documentation on product images](http://docs.shopify.com/api/product_image), we should be able to make POST and PUT calls directly to `/admin/products/#{id}/images.json` and `PUT /admin/products/#{id}/images/#{id}.json`. However, this doesn't seem to work currently with the API as the prefix for the `Image` class isn't properly being built. Thus, something like this...

```python
image = shopify.Image()
image.src = "http://example.com/example.png"
image.product_id = 123456789
image.save()
```

... tries to POST to `/admin/products//images.json` which returns a 406.

Looking at the source, I think a fix would be to implement the `prefix()` class method, similar to what's been done with the `Variant` class. Just wanted to run this by folks who might be more familiar with this to see if that might be a valid solution.

### PR DESCRIPTION
**Pull request by asiviero**
As @gavinballard points out, a small change in Image class makes it possible for it to behave just as the Variant class, so I added that code to it, tested on my dev store and wrote a test for it.

### CODE REVIEW

**Comment by kevinhughes27** [comment]
@awd for triage

**Comment by asiviero** [comment]
ping?

**Comment by kevinhughes27** [comment]
@joshubrown can you get someone on this

**Comment by flux627** [comment]
Is there anything preventing this from being merged? I'd really like to use this on the master branch.

**Comment by kevinhughes27** [comment]
I am ok with this.

**Pull request merged**
