### PR TITLE
Remove unused cgi import

### LINKED ISSUE #644: CGI is deprecated and will be removed in python 3.13
## Overview/summary
```
../usr/local/lib/python3.11/site-packages/shopify/collection.py:3
  /usr/local/lib/python3.11/site-packages/shopify/collection.py:3: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi
```
Looking around in the codebase, I only found this usage:
https://github.com/Shopify/shopify_python_api/blob/master/shopify/collection.py#L3
I don't think it's actually being used

## Motivation

I don't want to stop being able to update python

---

## Checklist

- [x] I have described this enhancement in a way that is actionable (if possible)

### PR DESCRIPTION
**Pull request by adamchainz**
### WHY are these changes introduced?

Fixes #644

### WHAT is this pull request doing?

Removing some imports that have not been used since the creation of the file in 164c7e288fcdd93feca8bf3cc7faec5722d2395d.

### Checklist

- [x] I have updated the CHANGELOG (if applicable)
- [x] I have followed the [Shopify Python](https://github.com/Shopify/shopify_python) guide

### CODE REVIEW

**Comment by adamchainz** [comment]
For reference here's the Python 3.11 release note about the deprecation: https://docs.python.org/3.11/whatsnew/3.11.html#modules .

**Comment by h55nick** [comment]
Can we get this merged in? Thanks all!

**Comment by ryantang30** [comment]
Bumping this as pytest gives a warning about this as well. Would appreciate if it can be merged in for next release. Thanks!

```

==================================================================================================== warnings summary ==================================================================================================== 
.venv\Lib\site-packages\shopify\collection.py:3
  C:\Users\Folder\.venv\Lib\site-packages\shopify\collection.py:3: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================== 1 passed, 1 warning in 0.69s ==============================================================================================
```

**Review by Arkham — APPROVED** [review]
Thanks!

**Pull request merged**
