### PR TITLE
Update README for security changes

### PR DESCRIPTION
**Pull request by ShayneP**
Updating README to reflect the changes to ```redirect_uri```, and added the optional ```state``` param.

@kevinhughes27 @awd

### CODE REVIEW

**Comment by kevinhughes27** [comment]
:+1:

**Comment by awd** [comment]
This PR should probably apply the same same feedback as in https://github.com/Shopify/shopify_api/pull/203 

Then LGTM :ship:

**Comment by ShayneP** [comment]
Updated to apply the same feedback as the other PR

**Comment by awd** [comment]
:shipit:

**Pull request merged**
