### PR TITLE
Adds suport to Shipping Zones (closes #126)

### LINKED ISSUE #126: Add support for the new Shipping Zone resource.
As per https://ecommerce.shopify.com/c/api-announcements/t/shipping-zones-api-and-changes-to-the-countries-api-307687.

### PR DESCRIPTION
**Pull request by asiviero**
Hey guys,

This was easier than I thought since most of the heavy lifting is done by pyactiveresource.

Did some basic testing with my dev account and data seems fine

### CODE REVIEW

**Comment by kevinhughes27** [comment]
Its pretty magical eh! Can you add a couple of tests? should be able to modify one of the other test files

**Comment by asiviero** [comment]
Does it make sense to have a test for this since shipping zones is just a get request, without being able to modify anything? I mean, I guess there's no test for countries either

**Comment by kevinhughes27** [comment]
Country should probably have a test as well! Its just a nice sanity check that it is generating the right url internally

**Comment by asiviero** [comment]
Let me work on it

**Comment by kevinhughes27** [comment]
Thanks!

**Comment by asiviero** [comment]
There you go, not sure if it's the right way of doing it but I tracked the function that should make the collection url and tested against it, let me know if it was the right way of doing it

**Comment by kevinhughes27** [comment]
I was thinking something more like this: https://github.com/Shopify/shopify_python_api/blob/master/test/article_test.py#L12

**Comment by asiviero** [comment]
I guess that's more like it

**Comment by kevinhughes27** [comment]
Nice!

**Pull request merged**
